ficha6: ficha6.o Queue.o Stack.o 
	gcc -Wall $^ -o $@


ficha6.o: ficha6.c
	gcc -Wall $^ -c -o $@

Queue.o: Queue.c
	gcc -Wall $^ -c -o $@

Stack.o: Stack.c
	gcc -Wall $^ -c -o $@

clean:
	rm -f Queue.o Stack.o ficha6.o ficha6
